version: "3.8"
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9001:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/mydatabase
      SONAR_JDBC_USERNAME: user
      SONAR_JDBC_PASSWORD: your_password
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /path/to/mongo-data:/data/db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgresContainer
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mydatabase
    volumes:
      - /path/to/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  festivalapp:
    build: .
    container_name: festivalAppContainer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

  reviewapp:
    build: /Users/victor/IdeaProjects/reviewapp
    container_name: reviewAppContainer
    depends_on:
      festivalapp:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      FESTIVAL_APP_BASE_URL: http://festivalapp:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql_data:
